apiVersion : apps/v1
kind: Deployment
metadata:
  name: emarionredotestproj 
spec:
  replicas: 1
  selector:
      matchLabels:
        app: emarionredotestproj
  template:
    metadata:
      labels:
        app: emarionredotestproj 
    spec:
      containers:
        - name: emarionredotestproj 
          image: rcontainer2.azurecr.io/emarionredotestproj
          ports:
          - containerPort: 80
